### ISSUE TITLE
This is not what it is generally understood by pushing, this is actually called pulling.

### ISSUE THREAD

**Issue by aguaviva** [G6EJD/ESP-Webserver-Push-Data#1]
More info here: https://en.wikipedia.org/wiki/Push_technology

"Push technology, or server push, is a style of Internet-based communication where the request for a given transaction is initiated by the publisher or central server. It is contrasted with pull/get, where the request for the transmission of information is initiated by the receiver or client."

**Comment by G6EJD** [comment]
First of all we don’t use github for general comments or debate, what is the issue your reporting?

In this example the ESP web server initiates an update to the client, yes the client made the initial request but thereafter all data was pushed to the client so it is a server push!

**Comment by G6EJD** [comment]
BTW if you study the web server code you will see that the client never seeks an update it’s all from the server to the client.

I think you really need to understand a subject before you launch into a simple quote from whatever source rather than making your own determination of the subject and stating your own thesis of what pushing data is. That way you will get a more positive response. I await your response.

**Comment by aguaviva** [comment]
I was expecting a more polite response but anyway... I hope this helps you and other people landing here.

I did look at the code and it looks like you are polling the server every second

`setInterval(function() {getSensorData();}, 1000); // Call the update function every set interval e.g. 1000mS or 1-sec`

This is called pulling.

**Comment by G6EJD** [comment]
Your not understanding this topic are you. The ESP is setup as a SERVER and once a client connects it (the Server) runs a script to send updated data to the clients screen, so it’s a classic data push. Your quoted the server code. Please take some time to understand before launching into an abrupt criticism without any context or explanation, anyone can do that, hence my in your words, less than polite responses.

**Comment by aguaviva** [comment]
I built way more advanced projects than this one(https://github.com/aguaviva/SousVide), I know what I am doing and I am trying to help you. 

What I quoted is actually javascript code that runs in the browser, and that is what initiates the reading and hence you are pulling, pushing is way harder to accomplish.

**Comment by G6EJD** [comment]
You need to learn how to open up a conversation so that it’s not blunt and curt, that way you will get a more positive response, it’s a life not technical skill. I don’t know which country your in, probably France, but cultural differences are no excuse for common courtesy, that’s all I’m saying.
